language: go

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

# Set configuration environment variables
env:
  - LANTERN_DBHOST=localhost LANTERN_DBPORT=5432 LANTERN_DBUSER=lantern LANTERN_DBPASSWORD= LANTERN_DBNAME=lantern LANTERN_DBSSLMODE=disable POSTGRES_PASSWORD=postgrespassword POSTGRES_USER=lantern POSTGRES_DB=lantern

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run -E gofmt
  - go test -v -race ./...  # Run all the tests with the race detector enabled
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --abort-on-container-exit