version: '3'

services:

  endpoint_querier:
    entrypoint:
      - "./main"
      - "./resources/TestEndpointSources.json"

  prometheus_postgresql_adapter:
    command:
      -pg-host=pg_prometheus
      -pg-password=${LANTERN_TEST_DBPASSWORD}
      -pg-database=${LANTERN_TEST_DBNAME}
      -pg-user=${LANTERN_TEST_DBUSER}
      -pg-prometheus-log-samples
